language: php

php:
    - 5.5.9

branches:
  only:
    - master

before_install:
  - phpenv config-rm xdebug.ini

install:
    - make install

script:
    - make test
    - make quality

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
